//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmITApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public Animal()
        {
            this.Food = new HashSet<Food>();
        }
    
        public string TypeAnimal { get; set; }
        public long IdAnimal { get; set; }
        public string Age { get; set; }
        public string Name { get; set; }
        public string StatusAnimal { get; set; }
        public Nullable<int> AmountOfPowerfeed { get; set; }
        public Nullable<int> AmountOfHay { get; set; }
        public Nullable<int> AmountOfOats { get; set; }
        public string IdBox { get; set; }
    
        public virtual Box Box { get; set; }
        public virtual ICollection<Food> Food { get; set; }
    }
}
