//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmITApp.EntityFrameworkV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Box = new HashSet<Box>();
        }
    
        public string IdBuilding { get; set; }
    
        public virtual ICollection<Box> Box { get; set; }
    }
}
