//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmITApp.EntityFrameworkV2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.Animal = new HashSet<Animal>();
        }
    
        public long IdFood { get; set; }
        public Nullable<int> Amount { get; set; }
        public string TypeFood { get; set; }
    
        public virtual ICollection<Animal> Animal { get; set; }
    }
}
